version: 2.1

aliases:
  - &defaults
    working_directory: ~/shortcut-client-js
    docker:
      - image: cimg/node:lts
  - &attach_workspace
    attach_workspace:
      at: ~/shortcut-client-js

orbs:
  node: circleci/node@4.7.0

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Lint
          command: yarn lint
  validate-schema:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Validate Schema
          command: yarn validate:schema
  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run Jest
          command: yarn test
  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build
          command: yarn build

workflows:
  tests:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - validate-schema:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - checkout
